---
version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s %(levelname)s %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    backupCount: 3
    level: INFO
    formatter: simple
    filename: 'bibbi.log'
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
root:
  level: INFO
  handlers:
    #- file
    - console
